language: java
git:
  depth: 10
branches:
  only:
    - develop
    - master
jdk:
  - oraclejdk8
after_success:
   - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
