image: gradle:6.9-jdk8

pipelines:
  default:
    - step:
        name: assemble all
        script: # simply build and compile
          - gradle clean
          - gradle assemble --parallel
    - step:
        name: tests
        script: # alright, test it
          - gradle test
