# This is a sample build configuration for Maven.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gradle:6.6-jdk8

pipelines:
  default:
    - step:
        name: assemble all
        script: # simply build and compile
          - ./gradlew clean
          - ./gradlew assemble --parallel
    - step:
        name: tests
        script: # alright, test it
          - ./gradlew test
