name: Build Project

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  CI: "1"
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cargo
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: "-Xmx3200m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      CI: true
    strategy:
      matrix:
        java: [ '8', '17' ]
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: show version of Java
        run: |
          java -version
          ./gradlew -version
      - name: compile it
        run: ./gradlew compileJava compileTestJava
      - name: run tests
        run: ./gradlew test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/build/test-results/test/*.xml
            **/build/test-results/**/*.trx
            **/build/test-results/**/*.json
