name: Build Project

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Assemble it
        run: ./gradlew assemble
      - name: Test it
        run: ./gradlew test
