name: Build Project

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  CI: "1"
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cargo
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JVM_OPTS: "-Xmx3200m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: show version of Java
        run: |
          java -version
          ./gradlew -version
      - name: compile it
        run: ./gradlew clean assemble
      - name: run tests
        run: ./gradlew test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/build/test-results/test/*.xml
            **/build/test-results/**/*.trx
            **/build/test-results/**/*.json


  build-via-buildah:
    name: Build in container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-new-image
          tags: v1 ${{ github.sha }}
          containerfiles: |
            ./zulu.Dockerfile
#          build-args: |
#            some_arg=some_value